export enum NotificationType {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
  TASK_COMMENTED = 'TASK_COMMENTED',
  TENANT_INVITED = 'TENANT_INVITED',
  MEMBER_JOINED = 'MEMBER_JOINED',
}
